/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package XDPJFLOTA.Flota;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import com.toedter.calendar.JDateChooser;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;

/**
 *
 * @author jazdz
 */
@SuppressWarnings("serial")
public class FlotaWindow extends javax.swing.JFrame {
	  private static final String SEP = ";";
    /**
     * Creates new form Flota
     */
    public FlotaWindow() {
    	setTitle("X DISC Flota v 1.0");
    	setLocation(350, 150);
    	getContentPane().setForeground(Color.DARK_GRAY);
    	getContentPane().setFont(new Font("Segoe UI", Font.PLAIN, 12));
    	getContentPane().setPreferredSize(new Dimension(1195, 600));
    	setResizable(false);
    	getContentPane().setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
    	
        initComponents();
    }
	DateTimeFormatter df = DateTimeFormatter.ofPattern("EEEE, dd.MM.yyyy");
	LocalDate data = LocalDate.now();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(18, 0, 501, 33);
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator1.setBounds(18, 39, 1157, 14);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel2.setBounds(18, 50, 78, 25);
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jComboBox1.setBounds(100, 50, 170, 25);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel3.setBounds(18, 86, 78, 25);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextField1.setBounds(100, 86, 170, 25);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel4.setBounds(292, 86, 78, 25);
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextField2.setBounds(374, 86, 170, 25);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel5.setBounds(18, 117, 78, 25);
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox2.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jComboBox2.setBounds(100, 117, 170, 25);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel6.setBounds(292, 117, 80, 25);
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox3.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jComboBox3.setBounds(374, 116, 170, 25);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel7.setBounds(576, 117, 90, 25);
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox4.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jComboBox4.setBounds(661, 117, 170, 25);
        jComboBox4.setEnabled(false);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel8.setBounds(18, 150, 78, 25);
        jTextField3 = new javax.swing.JTextField();
        jTextField3.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextField3.setBounds(100, 150, 444, 25);
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel9.setBounds(18, 186, 78, 25);
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel10.setBounds(18, 222, 78, 25);
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel11.setBounds(292, 186, 78, 25);
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextField4.setBounds(374, 186, 170, 25);
        
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel12.setBounds(292, 222, 78, 25);
        jTextField5 = new javax.swing.JTextField();
        jTextField5.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextField5.setBounds(374, 222, 170, 25);
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel13.setBounds(18, 258, 78, 25);
        jTextField6 = new javax.swing.JTextField();
        jTextField6.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextField6.setBounds(100, 260, 444, 25);
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(661, 260, 170, 25);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(18, 309, 811, 185);
        jTable1 = new javax.swing.JTable();
        
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel14.setBounds(879, 50, 296, 25);
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel15.setBounds(879, 117, 296, 25);
        jLabel16 = new javax.swing.JLabel();
        jLabel16.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel16.setBounds(879, 86, 296, 25);
        jLabel17 = new javax.swing.JLabel();
        jLabel17.addContainerListener(new ContainerAdapter() {
        	@Override
        	public void componentAdded(ContainerEvent e) {
        	}
        });
        jLabel17.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel17.setBounds(879, 150, 296, 25);
        jLabel18 = new javax.swing.JLabel();
        jLabel18.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel18.setBounds(879, 186, 296, 25);
        jLabel19 = new javax.swing.JLabel();
        jLabel19.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel19.setBounds(879, 222, 296, 25);
        jLabel20 = new javax.swing.JLabel();
        jLabel20.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel20.setBounds(879, 258, 296, 25);
        jLabel21 = new javax.swing.JLabel();
        jLabel21.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel21.setBounds(879, 294, 296, 25);
        jLabel22 = new javax.swing.JLabel();
        jLabel22.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel22.setBounds(879, 330, 296, 25);
        jLabel23 = new javax.swing.JLabel();
        jLabel23.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel23.setBounds(879, 366, 296, 25);
        jLabel24 = new javax.swing.JLabel();
        jLabel24.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel24.setBounds(879, 402, 296, 25);
        jLabel25 = new javax.swing.JLabel();
        jLabel25.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel25.setBounds(879, 474, 296, 25);
        jLabel26 = new javax.swing.JLabel();
        jLabel26.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel26.setBounds(879, 521, 296, 25);
        jLabel27 = new javax.swing.JLabel();
        jLabel27.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel27.setBounds(879, 557, 296, 25);
        jLabel28 = new javax.swing.JLabel();
        jLabel28.setHorizontalTextPosition(SwingConstants.CENTER);
        jLabel28.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel28.setFont(new Font("Segoe UI", Font.ITALIC, 12));
        jLabel28.setBounds(849, 3, 326, 30);
        jButton2 = new javax.swing.JButton();
        jButton2.setBounds(644, 521, 187, 25);
        jButton3 = new javax.swing.JButton();
        jButton3.setBounds(644, 557, 187, 25);
        jLabel29 = new javax.swing.JLabel();
        jLabel29.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel29.setBounds(879, 438, 296, 25);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("X DISC FLOTA - Aplkacja do rozliczania kosztów samochodów firmowych");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Samochód:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOYOTA AURIS WT89507" }));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Użytkownik 1:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Użytkownik 2:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Dział 1:");

        jComboBox2.setModel(new DefaultComboBoxModel(new String[] {"ODM", "ODM CD", "ODM Winyl", "X DISC", "X DISC CD", "X DISC Winyl", "PVD", "Zarząd", "Serwis"}));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              odblokuj();
            }
        });
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Dział 2:");

        jComboBox3.setModel(new DefaultComboBoxModel(new String[] {"-----", "ODM", "ODM CD", "ODM Winyl", "X DISC", "X DISC CD", "X DISC Winyl", "PVD", "Zarząd"}));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Koszty serwisu:");

        jComboBox4.setModel(new DefaultComboBoxModel(new String[] {"ODM", "ODM CD", "ODM Winyl", "X DISC", "X DISC CD", "X DISC Winyl", "PVD", "Zarząd"}));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Cel:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Data wydania:");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Data zdania:");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Stan licznika:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Stan licznika:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Uwagi:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Zapisz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					zapis();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTable1);
       
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Samochód:");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Użytkownik 2:");

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Użytkownik 1:");

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Dział 1:");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Dział 2:");

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Koszty serwisu:");

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Cel:");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Data wydania:");

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Stan licznika:");

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Data zdania:");

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Stan licznika:");

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Uwagi:");

        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Dane wprowadzono:");

        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Dane wprowadził:");

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText(data.format(df));

        jButton2.setBackground(new Color(173, 216, 230));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new Color(30, 144, 255));
        jButton2.setText("Panel rozliczenia kosztów");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                FlotaKosztyWindow flotakoszty = new FlotaKosztyWindow();
                flotakoszty.setVisible(true);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setText("Zgłoś uwagi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               FlotaKontaktWindow kontakt = new FlotaKontaktWindow();
               kontakt.setVisible(true);
            }
        });

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Kilometrów:");
        getContentPane().setLayout(null);
        getContentPane().add(jLabel20);
        getContentPane().add(jSeparator1);
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel28);
        getContentPane().add(jLabel8);
        getContentPane().add(jTextField3);
        getContentPane().add(jLabel5);
        getContentPane().add(jComboBox2);
        getContentPane().add(jLabel3);
        getContentPane().add(jTextField1);
        getContentPane().add(jLabel2);
        getContentPane().add(jComboBox1);
        getContentPane().add(jLabel4);
        getContentPane().add(jTextField2);
        getContentPane().add(jLabel6);
        getContentPane().add(jComboBox3);
        getContentPane().add(jLabel9);
        getContentPane().add(jLabel11);
        getContentPane().add(jTextField4);
        getContentPane().add(jLabel10);
        getContentPane().add(jLabel12);
        getContentPane().add(jTextField5);
        getContentPane().add(jLabel13);
        getContentPane().add(jTextField6);
        getContentPane().add(jLabel7);
        getContentPane().add(jComboBox4);
        getContentPane().add(jButton1);
        getContentPane().add(jLabel21);
        getContentPane().add(jLabel22);
        getContentPane().add(jLabel17);
        getContentPane().add(jLabel18);
        getContentPane().add(jLabel15);
        getContentPane().add(jLabel16);
        getContentPane().add(jLabel23);
        getContentPane().add(jLabel24);
        getContentPane().add(jLabel19);
        getContentPane().add(jLabel29);
        getContentPane().add(jScrollPane1);
        getContentPane().add(jLabel25);
        getContentPane().add(jLabel26);
        getContentPane().add(jLabel27);
        getContentPane().add(jButton3);
        getContentPane().add(jButton2);
        getContentPane().add(jLabel14);
        
        dateChooser = new JDateChooser();
        dateChooser.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        dateChooser.setBounds(100, 186, 170, 25);
        getContentPane().add(dateChooser);
        
        dateChooser_1 = new JDateChooser();
        dateChooser_1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        dateChooser_1.setBounds(100, 222, 170, 25);
        getContentPane().add(dateChooser_1);
        
        JSeparator jSeparator1_1 = new JSeparator();
        jSeparator1_1.setOrientation(SwingConstants.VERTICAL);
        jSeparator1_1.setBounds(849, 39, 20, 546);
        getContentPane().add(jSeparator1_1);
        
        jLabel13_1 = new JLabel();
        jLabel13_1.setForeground(new Color(102, 102, 102));
        jLabel13_1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jLabel13_1.setBounds(18, 521, 526, 25);
        getContentPane().add(jLabel13_1);
        String link = //"C:\\Users\\jazdz\\OneDrive\\Pulpit\\Projekty\\Flota\\XDISCFlota.csv";
        		"X:\\sekretariat\\Flota\\XDISCFlota.csv";
        BufferedReader br = null;
		try {
			br = new BufferedReader(new FileReader(link));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
   		String [] columnnames = {"L.P","Data wydania", "Data zdania", "Użytkownik 1", "Dział 1","Kilometrów"};
   		DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
   		TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
   		jTable1.setRowSorter(tr);
		int rowstoremove = model.getRowCount();
		for(int i=rowstoremove-1; i>=0; i--) {
			model.removeRow(i);
		}							
   		model.setColumnIdentifiers(columnnames);   
   		Object [] tableLines = br.lines().toArray();	       			       		       		
   		for (int i = 0; i < tableLines.length; i++) {       			 
   		String line = tableLines[i].toString().trim(); 
   		String [] datarow = line.split(";");       
   		model.addRow(datarow);
   		}
		List<FlotaClass> flota = ObslugaCSVFlota.wczytaj(link);
		int lp = jTable1.getRowCount();
		String slp = Integer.toString(lp);
		
		String slpp = slp;
		 
		for (FlotaClass emp : flota) {
			
			if(slpp.equals(emp.getLp())) {
				try {
					jTextField4.setText(emp.getLicznik2().replace(".0",""));
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			   			
		}
        
        numer();

        pack();
    }// </editor-fold>     
    

	@SuppressWarnings("unlikely-arg-type")
	public void zapis() throws IOException {
		
		@SuppressWarnings("deprecation")
		Locale local = new Locale("pl", "PL");
		FormatStyle style = FormatStyle.MEDIUM;
		DateTimeFormatter df1 = DateTimeFormatter
				.ofLocalizedDateTime(style)
				.withLocale(local);
		ZonedDateTime teraz = ZonedDateTime.now();
		
		numer();
		@SuppressWarnings("unused")
		DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-MM-yyyy");
		String dataczas = teraz.format(df1);
		String samochod = (String) jComboBox1.getSelectedItem();
		String user1 = jTextField1.getText();
		String user2 = jTextField2.getText();
		String department1 = (String) jComboBox2.getSelectedItem();
		String department2 = (String) jComboBox3.getSelectedItem();
		String department3 = (String) jComboBox4.getSelectedItem();
		String cel = jTextField3.getText();
		Date data1 = (Date) dateChooser.getDate();
		Date data2 = (Date) dateChooser_1.getDate();
		String mojadata1 = data1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate().toString().replace(".","-");
		String mojadata2 = data2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate().toString().replace(".","-");
		double licznik1 = Integer.parseInt(jTextField4.getText());
		double licznik2 = Integer.parseInt(jTextField5.getText());
		String uwagi = jTextField6.getText();
		
		String username = System.getProperty("user.name");
		
		double kilometry = licznik2 - licznik1;
		
		double kmdep1 = 0;
		double kmdep2 = 0;
		double kmdep3 = 0;
		
		if(jComboBox3.getSelectedItem().equals("-----")){
			 kmdep1 = kilometry;
			 kmdep2 = 0;
			 kmdep3 = 0;		 
			} 
		if(!jComboBox3.getSelectedItem().equals("-----")){			
			 kmdep1 = kilometry/2; 
			 kmdep2 = kilometry/2; 
			 kmdep3 = 0; }				 
		if(!jComboBox2.equals("Serwis")){
			 kmdep3 = kmdep1;
		}
		
		String Skmdep1 = Double.toString(kmdep1).replace(".", ",");
		String Skmdep2 = Double.toString(kmdep2).replace(".", ",");
		String Skmdep3 = Double.toString(kmdep3).replace(".", ",");
		String Skilometry = Double.toString(kilometry);
		
		 FileOutputStream plik = null;
			try {
				plik = new FileOutputStream(
						//"C:\\Users\\jazdz\\OneDrive\\Pulpit\\Projekty\\Flota\\XDISCFlota.csv",true);
						"X:\\sekretariat\\Flota\\XDISCFlota.csv", true);
			} catch (FileNotFoundException e) { 
				e.printStackTrace();
			}
			int lp = jTable1.getRowCount()+1;
			String slp = Integer.toString(lp);
			PrintWriter out = new PrintWriter(plik);
			
			jLabel13_1.setText("Dodano zapis nr: " + slp + ". Dziękuję.");

			out.print(slp);
			out.print(SEP);
			out.print(mojadata1);
			out.print(SEP);
			out.print(mojadata2);
			out.print(SEP);
			out.print(user1);
			out.print(SEP);
			out.print(department1);
			out.print(SEP);
			out.print(Skilometry);
			out.print(SEP);
			out.print(department2);
			out.print(SEP);
			if(jComboBox4.isEnabled()== true) {
			out.print(department3);
			out.print(SEP);	
			} else {
			out.print(SEP);	
			}
			out.print(cel);
			out.print(SEP);
			out.print(dataczas);
			out.print(SEP);
			out.print(licznik1);
			out.print(SEP);
			out.print(samochod);
			out.print(SEP);
			out.print(licznik2);
			out.print(SEP);
			out.print(user2);
			out.print(SEP);
			out.print(uwagi);
			out.print(SEP);
			out.print(Skmdep1);
			out.print(SEP);
			out.print(Skmdep2);
			out.print(SEP);
			if(jComboBox4.isEnabled()== true) {
			out.print(Skmdep3);
			out.print(SEP);	
			} else {
			out.print(SEP);	
			}
			out.print(username);
			out.println();
			out.close();
			
			String plik1 = //"C:\\Users\\jazdz\\OneDrive\\Pulpit\\Projekty\\Flota\\XDISCFlota.csv";
					"X:\\sekretariat\\Flota\\XDISCFlota.csv"; 
			
			BufferedReader br = null;
			try {
				br = new BufferedReader(new FileReader(plik1));
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
			
       		String [] columnnames = {"L.P","Data wydania", "Data zdania", "Użytkownik 1", "Dział 1","Kilometrów"};
       		DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
       		TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);      		
       		jTable1.setRowSorter(tr);
			int rowstoremove = model.getRowCount();
			for(int i=rowstoremove-1; i>=0; i--) {
				model.removeRow(i);
			}							
       		model.setColumnIdentifiers(columnnames);   
       		Object [] tableLines = br.lines().toArray();	       			       		       		
       		for (int i = 0; i < tableLines.length; i++) {       			 
       		String line = tableLines[i].toString().trim(); 
       		String [] datarow = line.split(";");       
       		model.addRow(datarow);
       		}
       		       		
       		String link = //"C:\\Users\\jazdz\\OneDrive\\Pulpit\\Projekty\\Flota\\XDISCFlota.csv";
       				"X:\\sekretariat\\Flota\\XDISCFlota.csv";
			
    		List<FlotaClass> flota = ObslugaCSVFlota.wczytaj(link);
    	   		
    		String slpp = slp;
    		 
    		for (FlotaClass emp : flota) {
    			
    			if(slpp.equals(emp.getLp())) {
    				jTextField4.setText(emp.getLicznik2().replace(".0",""));
    			}
    			   			
    		}
    	jTextField1.setText(null);	
    	jTextField2.setText(null);
    	jTextField3.setText(null);	
    	jTextField5.setText(null);
    	jTextField6.setText(null);
	}
	
	public void odblokuj() {
		
		if(jComboBox2.getSelectedItem().equals("Serwis")) {
			jComboBox4.setEnabled(true);
		} else {
			jComboBox4.setEnabled(false);
		}		
	}
	
	public void numer() {
		String plik1 = //"C:\\Users\\jazdz\\OneDrive\\Pulpit\\Projekty\\Flota\\XDISCFlota.csv";
				"X:\\sekretariat\\Flota\\XDISCFlota.csv"; 
		
		BufferedReader br = null;
		try {
			br = new BufferedReader(new FileReader(plik1));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
   		String [] columnnames = {"L.P","Data wydania", "Data zdania", "Użytkownik 1", "Dział 1","Kilometrów"};
   		DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
   		TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
   		jTable1.setRowSorter(tr);
		int rowstoremove = model.getRowCount();
		for(int i=rowstoremove-1; i>=0; i--) {
			model.removeRow(i);
		}							
   		model.setColumnIdentifiers(columnnames);   
   		Object [] tableLines = br.lines().toArray();	       			       		       		
   		for (int i = 0; i < tableLines.length; i++) {       			 
   		String line = tableLines[i].toString().trim(); 
   		String [] datarow = line.split(";");       
   		model.addRow(datarow);
   		}
   		
   		
   		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
		  public void mouseClicked(java.awt.event.MouseEvent evt) {
		try {
			
		String link = //"C:\\Users\\jazdz\\OneDrive\\Pulpit\\Projekty\\Flota\\XDISCFlota.csv";
				"X:\\sekretariat\\Flota\\XDISCFlota.csv";
						
		List<FlotaClass> flota = ObslugaCSVFlota.wczytaj(link);
						  
		Object lp = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
		 
		for (FlotaClass emp : flota) { 
			
			if(lp.equals(emp.getLp())) {
			jLabel14.setText("Samochód: " + emp.getSamochod());
			jLabel16.setText("Użytkownik 1: " + emp.getUser1());
			jLabel15.setText("Użytkownik 2: " + emp.getUser2());
			jLabel17.setText("Dział 1: " + emp.getDept1());
			jLabel18.setText("Dział 2: " + emp.getDept2());
			jLabel19.setText("Koszt Serwisu: " + emp.getDept3());
			jLabel20.setText("Cel: " + emp.getCel());
			jLabel21.setText("Data wydania: " + emp.getDatawydania().toString());
			jLabel22.setText("Stan licznika: " + emp.getLicznik1());
			jLabel23.setText("Data zdania: " + emp.getDatazdania().toString());
			jLabel24.setText("Stan licznika: " + emp.getLicznik2());
			jLabel29.setText("Kilometrów: " + String.valueOf(emp.getKm()));
			jLabel25.setText("Uwagi: " + emp.getUwagi());
			jLabel26.setText("Dane wprowadzono: " + emp.getDataczas());
			jLabel27.setText("Dane wprowadził: " + emp.getLoger());
			}
			
		}
		  		  
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
		  }
		});

	}
	

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                                                                                                                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlotaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlotaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlotaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlotaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlotaWindow().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabel13_1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private static javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private JDateChooser dateChooser;
    private JDateChooser dateChooser_1;
}
